---
kind: pipeline
name: documentation

platform:
  os: linux
  arch: amd64

steps:
- name: markdownlint
  image: node:lts-alpine
  commands:
  - npm install -g markdownlint-cli
  - markdownlint -p .gitignore 'README.md'

- name: spellcheck
  image: node:lts-alpine
  commands:
  - npm install -g spellchecker-cli
  - spellchecker --files 'README.md' -d .dictionary -p spell indefinite-article syntax-urls frontmatter --frontmatter-keys title --no-suggestions
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error

trigger:
  ref:
  - refs/heads/master

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack:1
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- documentation

---
kind: signature
hmac: ddd13992259a6036bc4920d5d28b356c1d4b3145333e8a812a5ddd4d7f116dd8

...
